engines:
    config:
      languages:
      - ruby
        #mass_threshold: 30
      - javascript
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "mejelly/app/**.rb"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
