engines:
  brakeman:
    enabled: true
    paths:
    - "mejelly"
  bundler-audit:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - "mejelly/**.rb"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
