engines:
  brakeman:
    enabled: true
    config:
      path: mejelly
  bundler-audit:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - mejelly/**
  - "**.rb"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
