language: ruby
branches:
  only:
    - ps1
    - mejelly
sudo: required
services:
  - docker
env:
  matrix:
  - global:
    - DOCKER_COMPOSE_VERSION: 2
    - REPO=mrteera/web16-06-$TRAVIS_BRANCH
    - COMMIT=${TRAVIS_COMMIT::8}
    - if [[ "$TRAVIS_BRANCH" == "ps1" ]]; then REPO_DIR=PS/ps1; fi
    - if [[ "$TRAVIS_BRANCH" == "mejelly" ]]; then REPO_DIR=mejelly; fi
before_install:
  - openssl aes-256-cbc -K $encrypted_b9d256b383d7_key -iv $encrypted_b9d256b383d7_iv -in .travis/web16_deploy_key.enc -out .travis/web16_deploy_key -d
before_script:
  - docker build -t $REPO:$COMMIT -f $REPO_DIR/compose/passenger/Dockerfile .
  - cd $REPO_DIR
  - docker-compose -f docker-compose.yml up -d
script:
  - docker-compose -f docker-compose.yml run web rubocop -RDS --fail-fast
  - docker-compose -f docker-compose.yml run web haml-lint app/views/
  - if [[ "$TRAVIS_BRANCH" == "ps1" ]]; then docker-compose -f docker-compose.yml run web rails test; fi
  - if [[ "$TRAVIS_BRANCH" == "mejelly" ]]; then docker-compose -f docker-compose.yml run web rspec; fi
  - docker-compose -f docker-compose.yml run web rails cucumber
after_script:
  - docker-compose down
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $REPO
  - bash deploy.sh
