language: ruby

addons:
  postgresql: "9.4"

rvm:
  - 2.3.1

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd PS/youtube
  - bundle install --jobs=3 --retry=3

script:
  - rubocop -RDS
  - haml-lint app/views/
  - rails test
  - rails cucumber
