language: ruby
branches:
  only:
    - ps1
sudo: required
services:
  - docker
env:
  matrix:
  - global:
    - DOCKER_COMPOSE_VERSION: 2
    - REPO=mrteera/web16-06
    - COMMIT=${TRAVIS_COMMIT::8}
before_script:
  - if [[ "$TRAVIS_BRANCH" == "ps1" ]]; then cd PS/ps1; fi
  - docker-compose -f docker-compose.yml up --build -d
  - docker-compose -f docker-compose.yml run web rails db:create db:migrate
script:
  - docker-compose -f docker-compose.yml run bash tests.sh
after_script:
  - docker-compose down
