version: '2'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/docker/postgres-data:/var/lib/postgresql/data
  web:
    image: {}
    command: /start-production.sh
    depends_on:
      - db
  nginx:
    image: nginx
    depends_on:
      - web
    volumes:
     - ./compose/nginx/ps1.conf:/etc/nginx/conf.d/ps1.conf
    ports:
     - "0.0.0.0:3001:80"
    dns: 8.8.8.8
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/ps1.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
